databases:
 - name: schemabook
   databaseName: schemabook
   user: schemabook_user

services:
 - type: web
   name: schemabook
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: schemabook
         property: postgres://schemabook_user:LCDiOgxP2EOiwnNj2zSlMy4KJ5iwOhfu@dpg-c2289fm1aaa42cr2a0s0/schemabook
     - key: RAILS_MASTER_KEY
       sync: false
