databases:
 - name: schemabook
   databaseName: schemabook
   user: schemabook_user

services:
 - type: web
   name: schemabook
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: schemabook
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false
     - key: REDIS_URL
       fromService:
          type: redis
          name: schemabook
          property: connectionString
