---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/schemas":
    get:
      summary: list schemas
      tags:
      - Schemas
      description: Retrieves all schemas for the given user
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - name: schema-1
                    description: lorem ipsum
                    id: 2cgt6jwzzlvs
                    format:
                      name: json
                    created_at: '2024-01-23T17:00:37.881Z'
                    production: false
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                test_example:
                  value:
                    status: 401
                    error: Unauthorized
    post:
      summary: create schema
      tags:
      - Schemas
      description: Creates a formatted schema associated with a given service
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    name: my_schema
                    description:
                    id: i0x4xl96ouqp
                    format:
                      name: json
                    created_at: '2024-01-23T17:00:38.034Z'
                    production: false
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                test_example:
                  value:
                    status: 401
                    error: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                service_id:
                  type: string
                production:
                  type: boolean
                format:
                  type: string
                body:
                  type: string
  "/api/schemas/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: schema
      tags:
      - Schemas
      description: Retrieves a specific schema by id
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    name: schema-5
                    description: lorem ipsum
                    id: tk2h8qnnnhf9
                    format:
                      name: json
                    created_at: '2024-01-23T17:00:38.110Z'
                    production: false
  "/api/services":
    get:
      summary: list services
      tags:
      - Services
      description: Retrieves all services for the given user
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - name: service-3
                    description:
                    id: 74lj4nfg2l1x
                    team_name: team-6
                    created_at: '2024-01-23T17:00:38.135Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                test_example:
                  value:
                    status: 401
                    error: Unauthorized
  "/api/services/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: service
      tags:
      - Services
      description: Retrieves a specific service by id
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    name: service-5
                    description:
                    id: uiq4hagq3imw
                    team_name: team-8
                    created_at: '2024-01-23T17:00:38.173Z'
servers:
- url: https://www.schemabook.com
