---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/schemas":
    get:
      summary: list schemas
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - name: schema-1
                description: lorem ipsum
                public_id: umc8nfl6mtp5
                format:
                  name: json
                created_at: '2023-10-12T13:51:04.555Z'
                production: false
servers:
- url: https://www.schemabook.com
