---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/schemas":
    get:
      summary: list schemas
      tags:
      - Schemas
      description: Retrieves all schemas for the given user
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
    post:
      summary: create schema
      tags:
      - Schemas
      description: Creates a formatted schema associated with a given service
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Successful
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                service_id:
                  type: string
                production:
                  type: boolean
                format:
                  type: string
                body:
                  type: string
  "/api/schemas/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: schema
      tags:
      - Schemas
      description: Retrieves a specific schema by id
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
  "/api/services":
    get:
      summary: list services
      tags:
      - Services
      description: Retrieves all services for the given user
      parameters:
      - name: x-api-token
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
servers:
- url: https://www.schemabook.com
